---
- name: Ensure nginx is installed
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Deploy nginx config
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/nginx/sites-available/{{ item }}
    mode: "0600"
  loop:
    - status-page.conf
  notify: Restart nginx
  tags:
    - config

- name: Remove default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx
  tags:
    - config

- name: Configure site symlinks
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
    mode: "0600"
  loop:
    - status-page.conf
  notify: Restart nginx
  tags:
    - config

- name: Enable nginx service
  ansible.builtin.service:
    name: nginx
    enabled: true
