---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Reload network
  ansible.builtin.command:
    cmd: "networkctl reload"
  register: reload_out
  changed_when: true
  failed_when: reload_out.rc != 0

- name: Restart pppd
  ansible.builtin.service:
    name: ppp@telekom
    state: restarted

- name: Restart wg-quick@wg0
  ansible.builtin.service:
    name: wg-quick@wg0
    state: restarted
