---
- name: Install required packages
  ansible.builtin.apt:
    package: nftables
    state: present

- name: Deploy firewall config
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "0644"
    trim_blocks: true
    lstrip_blocks: true
  notify: Reload firewall
  tags:
    - config

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: true
    sysctl_file: "/etc/sysctl.d/ansible.conf"
  tags:
    - sysctl
  loop:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

- name: Enable & run nftables
  ansible.builtin.service:
    name: nftables
    enabled: true
    state: started
