---
- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Copy systemd target
  ansible.builtin.copy:
    src: keepalived.target
    dest: /etc/systemd/system/keepalived.target
    mode: "0644"
  tags:
    - systemd

- name: Include DHCP tasks
  ansible.builtin.include_tasks:
    file: "dhcp.yml"
    apply:
      tags:
        - dhcp
        - systemd
  tags:
    - dhcp
    - systemd

- name: Include PPP tasks
  ansible.builtin.include_tasks:
    file: ppp.yml
    apply:
      tags:
        - ppp
        - systemd
  tags:
    - ppp
    - systemd

- name: Deploy configuration file
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  notify: Reload keepalived
  tags:
    - config

- name: Create /var/lib/keepalived
  ansible.builtin.file:
    path: /var/lib/keepalived
    state: directory
    mode: "0755"
  tags:
    - config

- name: Copy notify script
  ansible.builtin.copy:
    src: notify_script.sh
    dest: /var/lib/keepalived/{{ vrrp_notify_script_name }}
    mode: "0755"
  tags:
    - config
  notify: Reload keepalived

- name: Enable keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    enabled: true
  notify: Restart keepalived
