---
- name: Disable PPP service
  ansible.builtin.systemd_service:
    name: ppp@telekom.service
    enabled: false
    state: stopped

- name: Create systemd override dir for PPP
  ansible.builtin.file:
    path: /etc/systemd/system/ppp@telekom.service.d
    state: directory
    mode: "0755"

- name: Copy systemd overrides
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/ppp@telekom.service.d/override_keepalived.conf
    mode: "0644"

- name: Re-Enable PPP service
  ansible.builtin.systemd_service:
    name: ppp@telekom.service
    enabled: true
    daemon_reload: true
