---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Reload network
  ansible.builtin.command:
    cmd: "networkctl reload"
  register: reload_out
  changed_when: true
  failed_when: reload_out.rc != 0

- name: Restart pppd
  ansible.builtin.service:
    name: ppp@telekom
    state: restarted

- name: Restart wg-quick@wg0
  ansible.builtin.service:
    name: wg-quick@wg0
    state: restarted
  notify: Print firewall status

- name: Collect FW status
  ansible.builtin.command:
    cmd: "nft list ruleset"
  register: nft_ruleset
  changed_when: true
  listen: Print firewall status

- name: Print FW status
  ansible.builtin.debug:
    var: nft_ruleset.stdout_lines
  listen: Print firewall status
